# Generated by Django 3.2.5 on 2021-07-30 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='status',
        ),
        migrations.AddField(
            model_name='alert',
            name='created',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alert',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alert',
            name='triggered',
            field=models.BooleanField(default=False),
        ),
    ]
